In [57]:
#DOSADO, MICHAEL VINCENT    BSCS IV   CMSC197 ML QUIZ1

#PART 1


%pylab inline

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [42]:
y_hat = np.array(np.linspace(-1, 1, num=20))
y_hat

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

In [43]:
y = np.array(np.linspace(0,1,num=20))
y

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [8]:
y_hat.shape

(20,)

In [9]:
y_hat.ndim

1

In [10]:
y.shape

(20,)

In [11]:
y.ndim

1

In [25]:
#Function to return the loss value using the MSE (mean squared error) formula
def meanSquarederror(yhat,y):  
    L = np.sum((y_hat-y)**2)/len(y_hat)
    return L
meanSquarederror(y_hat,y)

0.3421052631578948

In [28]:
#Function to return the loss value using the MAE (mean absolute error) formula
def meanAbsoluteError(yhat,y):
    L = np.sum(np.absolute(y_hat-y))/len(y_hat)
    return L
meanAbsoluteError(y_hat,y)

0.4999999999999999

In [39]:
#Function to return the loss value using the MSLE (mean squared logarithmic error) formula
def meanSquaredlogarithmicError(yhat,y):
    L = np.sum((np.log(yhat+1)-(np.log(y+1)))**2)/len(yhat)
    if L == np.inf:
        return "Error: negative values => Target variable should be non-negative."
    else:
        return L
meanSquaredlogarithmicError(y_hat,y)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_20432\3610067111.py:3: RuntimeWarning: divide by zero encountered in log
  L = np.sum((np.log(yhat+1)-(np.log(y+1)))**2)/len(yhat)


'Error: negative values => Target variable should be non-negative.'

In [54]:
#Function to return the loss value using the MAPE (mean absolute percentage error) formula
def meanAbsolutepercentageError(yhat,y):
    print(len(y))
    L = (100*np.sum(np.absolute((yhat-y)/y)))/len(yhat)
    print(np.sum(np.absolute((yhat-y)/y)))
    return L

meanAbsolutepercentageError(y_hat,y)


20
inf


C:\Users\ASUS\AppData\Local\Temp\ipykernel_20432\283485930.py:4: RuntimeWarning: divide by zero encountered in true_divide
  L = (100*np.sum(np.absolute((yhat-y)/y)))/len(yhat)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_20432\283485930.py:5: RuntimeWarning: divide by zero encountered in true_divide
  print(np.sum(np.absolute((yhat-y)/y)))


inf

In [55]:
#PART 2

In [96]:
#Create 1D Array M using arange function
M = np.arange(1,17)

#Reshape M into 4x4 array and store it to N
N = M.reshape(4,4)

print(N)
print(N.ndim)
N.shape


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
2


(4, 4)

In [103]:
#GET 2nd Row on N
N[1,:]

array([5, 6, 7, 8])

In [112]:
#Get the minimum values for each column of N
np.amin(N,axis=0)

array([1, 2, 3, 4])

In [114]:
#Get the locations of the minimum values for each column of N
np.where(N == np.amin(N,axis=0))

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [117]:
#Get the average of the whole matrix
ave = np.mean(N)
ave

8.5

In [136]:
#Create a vector V with 4 elements, each element is 1
list1 = [1, 1, 1,1]
V = np.array(list1)
print(V)


[1 1 1 1]


In [137]:
#Take the dot product of N and V
dotProdNV = np.dot(N,V)
print(N)
print(V)
dotProdNV

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[1 1 1 1]


array([10, 26, 42, 58])