In [140]:
#DOSADO, MICHAEL VINCENT    BSCS IV   CMSC197 ML QUIZ1

#PART 1

#code to start pylab libraries
%pylab inline

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [144]:
#Create 2 2D arrays, y_hat and y
#• y_hat 
#Initialize y_hat with 20 linearly spaced numbers between -1 and 1
y_hat = np.array(np.linspace(-1, 1, num=20)) #Use of np.linspace to get the evenly spaced values of 20 items
y_hat                                        #print/ouput array

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

In [145]:
#Create 2 2D arrays, y_hat and y
#• y 
#Initialize y with 20 linearly spaced numbers between 0 and 1
y = np.array(np.linspace(0,1,num=20)) #Use of np.linspace to get the evenly spaced values of 20 items
y                                     #print/ouput array

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [149]:
#Compute for the shape and dimension of y_hat
y_hat_shape = y_hat.shape  #y_hat SHAPE  
y_hat_shape

(20,)

In [150]:
#Compute for the shape and dimension of y_hat
y_hat_dimension =  y_hat.ndim    #y_hat DIMENSION
y_hat_dimension

1

In [151]:
#Compute for the shape and dimension of y
y.shape

(20,)

In [152]:
##Compute for the shape and dimension of y
y.ndim

1

In [156]:
#NOTE: since it is needed that array must have the no. of items N, then we can use the len(array) function to get N

#Function to return the loss value using the MSE (mean squared error) formula
def meanSquarederror(yhat,y):           #yhat and y as parameters
    L = np.sum((y_hat-y)**2)/len(y_hat) #variable L to get the result of the formula
    return L                            #return result L  or  Loss value L
meanSquarederror(y_hat,y)

0.3421052631578948

In [28]:
#Function to return the loss value using the MAE (mean absolute error) formula
def meanAbsoluteError(yhat,y):                  #yhat and y as parameters
    L = np.sum(np.absolute(y_hat-y))/len(y_hat) #variable L to get the result of the formula
                                                #use of np.sum and np.absolute
    return L                                    #return loss value L
meanAbsoluteError(y_hat,y)

0.4999999999999999

In [39]:
#Function to return the loss value using the MSLE (mean squared logarithmic error) formula
def meanSquaredlogarithmicError(yhat,y):
    L = np.sum((np.log(yhat+1)-(np.log(y+1)))**2)/len(yhat)
    if L == np.inf:                            #error catch for target variables that are negative
        return "Error: negative values => Target variable should be non-negative."
    else:
        return L        #return loss value L for non-negative values
meanSquaredlogarithmicError(y_hat,y)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_20432\3610067111.py:3: RuntimeWarning: divide by zero encountered in log
  L = np.sum((np.log(yhat+1)-(np.log(y+1)))**2)/len(yhat)


'Error: negative values => Target variable should be non-negative.'

In [155]:
#Function to return the loss value using the MAPE (mean absolute percentage error) formula
def meanAbsolutepercentageError(yhat,y):
    L = (100*np.sum(np.absolute((yhat-y)/y)))/len(yhat)
    return L                               #return loss value L

meanAbsolutepercentageError(y_hat,y)


C:\Users\ASUS\AppData\Local\Temp\ipykernel_20432\2854010983.py:3: RuntimeWarning: divide by zero encountered in true_divide
  L = (100*np.sum(np.absolute((yhat-y)/y)))/len(yhat)


inf

In [158]:
#PART 2

In [157]:
#Create 1D Array M using arange function
M = np.arange(1,17)

#Reshape M into 4x4 array and store it to N
N = M.reshape(4,4)


N.shape


(4, 4)

In [103]:
#GET 2nd Row on N
N[1,:]

array([5, 6, 7, 8])

In [112]:
#Get the minimum values for each column of N
np.amin(N,axis=0)

array([1, 2, 3, 4])

In [114]:
#Get the locations of the minimum values for each column of N
np.where(N == np.amin(N,axis=0))

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [117]:
#Get the average of the whole matrix
ave = np.mean(N)
ave

8.5

In [160]:
#Create a vector V with 4 elements, each element is 1
list1 = [1, 1, 1,1]
V = np.array(list1)
V


array([1, 1, 1, 1])

In [137]:
#Take the dot product of N and V
dotProdNV = np.dot(N,V)
print(N)
print(V)
dotProdNV

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[1 1 1 1]


array([10, 26, 42, 58])